version: '3'

services:
  ten_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.5.0
    container_name: ten_agent_dev
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
    working_dir: /app
    env_file:
      - .env
    networks:
      - ten_agent_network
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
  ten_agent_playground:
    image: ghcr.io/ten-framework/ten_agent_playground:0.8.0-98-gddb26d7
    container_name: ten_agent_playground
    restart: always
    ports:
      - "3011:3000"
    networks:
      - ten_agent_network
    environment:
      - AGENT_SERVER_URL=http://ten_agent_dev:8081
      - TEN_DEV_SERVER_URL=http://ten_agent_dev:49483
  ten_agent_demo:
    image: ghcr.io/ten-framework/ten_agent_demo:0.8.0-34-gfc5b116
    container_name: ten_agent_demo
    restart: always
    ports:
      - "3009:3000"
    networks:
      - ten_agent_network
    environment:
      - AGENT_SERVER_URL=http://ten_agent_dev:8081
  # ten_graph_designer:
  #   image: ghcr.io/ten-framework/ten_graph_designer:4cc33b8
  #   container_name: ten_graph_designer
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - ten_agent_network
  #   environment:
  #     - TEN_DEV_SERVER_URL=http://ten_agent_dev:49483
networks:
  ten_agent_network:
    driver: bridge
